# Generated by Django 4.1.7 on 2023-03-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('popularity', models.PositiveIntegerField()),
                ('email_verified', models.BooleanField(default=False)),
                ('friends', models.ManyToManyField(blank=True, to='users.usermodel')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
