# Generated by Django 4.1.7 on 2023-03-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportmodel_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportmodel',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
